id = "bruno"
name = "Bruno"
description = "Bru language support and Bruno CLI tasks for Zed."
version = "0.1.0"
schema_version = 1
authors = ["byeval"]
repository = "https://github.com/byeval/bruno-zed"

[grammars.bru]
repository = "https://github.com/byeval/tree-sitter-bru"
rev = "5ed48a02b69dd4021742a7982c2606e638852317"
